# Ejercicios Python 2

Resuelve cada ejercicio en su celda y añade las pruebas necesarias para comprobar que funciona correctamente. Indica en un comentario la dificultad encontrada (del 1 al 5).

## Función que recibe una lista y devuelve otra eliminando sus duplicados

In [2]:
import numpy as np

def sin_duplicados(lista):
    return np.unique(lista)
        
#pruebas        
print (sin_duplicados(np.array([1,3,4,3,5,5,2,1,3,2,7,8,5])))
print (sin_duplicados(np.array(["verde","azul","gris","azul","rojo","negro","rojo"])))


[1 2 3 4 5 7 8]
['azul' 'gris' 'negro' 'rojo' 'verde']


## Función que recibe una matriz de NumPy y devuelve otra sustituyendo los valores repetidos por NaN

In [3]:
import numpy as np

def matriz_sin_duplicados(matriz):
    
    matriz_sin_duplicados=np.empty(matriz.shape,dtype=float) #creamos una matriz vacía con el tamaño de la matriz pasada y de tipo float para que no falle al insertar nan.
    lista_compare = set() # declaramos una colección contra la que compararemos la matriz  

    for fil, fila in enumerate(matriz): #recorremos las filas de la matris
        for col, elem in enumerate(fila): #recorremos los elementos de cada fila
            if elem in lista_compare: 
                matriz_sin_duplicados[fil,col] = np.nan #si el elemento está en la colección de elementos a comparar, asignamos NaN a ese elemento
            else:    
                matriz_sin_duplicados[fil,col] = elem #si no está, nos quedamos con el elemento
            lista_compare.add(elem) #añadimos el elemento a la lista a comparar para que no se vuelva a insertar
    return matriz_sin_duplicados

#pruebas

print(matriz_sin_duplicados(np.array([[5, 6, 8], [8, 5, 3], [9, 10, 3]])))
print(matriz_sin_duplicados(np.array([[1, 1, 2], [2, 1, 2], [3, 4, 3]])))

[[ 5.  6.  8.]
 [nan nan  3.]
 [ 9. 10. nan]]
[[ 1. nan  2.]
 [nan nan nan]
 [ 3.  4. nan]]


## Función que recibe una lista y devuelve un diccionario con el número de veces que aparece cada elemento.
Las claves del diccionario deben ser los elementos de la lista y los valores deben ser el número de veces que aparece dicho elemento en la lista

In [4]:
import numpy as np

def lista_a_diccionario(lista):
    #con unique de nuestra lista almacenamos los elementos únicos en la lista elementos y 
    #con el parámetro return_counts activo, almacenamos las veces que se repiten en la variable veces
    elementos, veces = np.unique(lista, return_counts=True) 
    #con zip se crean tuplas de los valores de ambas listas (elemento,vez) y dict los convierte a diccionario
    return dict((zip(elementos, veces)))
     
#pruebas   
print (lista_a_diccionario(np.array([1,2,5,5,4,5,6,7,2,3,3,4,4])))
print (lista_a_diccionario(np.array(["verde","azul","gris","azul","rojo","negro","rojo","rojo"])))


{1: 1, 2: 2, 3: 2, 4: 3, 5: 3, 6: 1, 7: 1}
{'azul': 2, 'gris': 1, 'negro': 1, 'rojo': 3, 'verde': 1}


## Función que recibe dos matrices cuadradas (NxN) y devuelve una tercera matriz que contiene el valor 1 en las posiciones en que el valor de A y B coinciden y 0 en caso contrario.

In [3]:
import numpy as np

def valores_iguales_matriz(matriz1, matriz2):
    matriz_comparacion = np.where(matriz1==matriz2,1,0) # si se cumple la condición devuelve 1 y si no 0
    return matriz_comparacion 

# Tests
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Matriz 3x3
matriz2 = np.array([[1, 5, 6], [7, 5, 9], [1, 2, 9]]) # Matriz 3x3

print(valores_iguales_matriz(matriz1, matriz2)) # Debería mostrar una matriz identidad
#para poder hacer el assert con arrays numpy debemos comparar (array1 & array2).all
assert (valores_iguales_matriz(matriz1, matriz2) & np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])).all


[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Función que recibe una matriz y busca sus puntos de silla o *saddle points* (máximos de su fila y mínimos de su columna o viceversa). Debe devolver una lista de tuplas con las coordenadas de los puntos de silla.

## 

In [22]:
import numpy as np

def devuelve_puntos_silla(matriz, max_fila=True):
    puntos_silla = []

    #recorremos las filas
    for i, fila in enumerate(matriz):
        # si max_fila es True buscamos maximo fila y mínimo columna, si no, al revés)
        if max_fila:
            maximo_fila = fila.max() #nos quedamos con el valor máximo de cada fila 
            for j in [j for j, valor in enumerate(fila) if fila[j]==maximo_fila]: #buscamos los índices de la fila dónde está el valor máximo (que serán la columna)
                if maximo_fila == matriz[:,j].min(): #con slicing buscamos el mínimo de los valores de esa columna, si coincide con nuestro máximo será el punto de silla
                    puntos_silla.append((i, j)) 
        else:
            minimo_fila = fila.min() #nos quedamos con el valor mínimo de cada fila 
            for j in [j for j, valor in enumerate(fila) if fila[j]==minimo_fila]: #buscamos los índices de la fila dónde está el valor mínimo (que serán la columna)
                if minimo_fila == matriz[:,j].max(): #con slicing buscamos el máximo de los valores de esa columna, si coincide con nuestro mínimo será el punto de silla
                    puntos_silla.append((i, j)) 

    return puntos_silla

#pruebas

print(devuelve_puntos_silla(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))) # (0,2) el 3 es el máximo de su fila y mínimo de su columna 
assert devuelve_puntos_silla(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])) == [(0, 2)]
print(devuelve_puntos_silla(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),False)) #(2,0) el 7 es el mínimo de su fila y máximo de su columna
assert devuelve_puntos_silla(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),False) == [(2, 0)]


[(0, 2)]
[(2, 0)]


## 